- name: 'Index'
  title: '首页'
  disabled: false
  icon: 'compass'
  url: '/'
- name: 'User'
  title: '用户管理'
  disabled: false
  icon: 'user'
  children:
    - name: 'User'
      title: '用户管理'
      disabled: false
      icon: 'user'
      url: '/user'
    - name: 'UserGroup'
      title: '用户组管理'
      disabled: false
      icon: 'user'
      url: '/user/group'
- name: 'System'
  title: '系统'
  disabled: false
  icon: 'setting'
  children:
    - name: 'Job'
      title: 定时任务管理
      disabled: false
      url: '/system/job'
      icon: 'user'
      children:
        - name: AuthGroupAdd
          title: 权限组添加
          disabled: false
        - name: AuthGroupDel
          title: 权限组删除
          disabled: false
        - name: AuthGroupUpdate
          title: 权限组修改
          disabled: true
        - name: AuthGroupList
          title: 权限组列表
          disabled: true
